-- PostgreSQL schema for igb-busca-go.
-- Ports the production MySQL `gnosis` database 1:1 (same schema, table,
-- column, index and constraint names; AUTO_INCREMENT -> IDENTITY).
--
--   psql "$CONNECTION_STRING" -f schema.sql

CREATE SCHEMA IF NOT EXISTS gnosis;

CREATE TABLE IF NOT EXISTS gnosis.books (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  perfil varchar(45),
  driveid varchar(255)
);

CREATE TABLE IF NOT EXISTS gnosis.pages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id integer,
  page_number integer,
  page_text text,
  CONSTRAINT book_id FOREIGN KEY (book_id) REFERENCES gnosis.books (id)
);

CREATE INDEX IF NOT EXISTS book_id_idx ON gnosis.pages (book_id);

CREATE TABLE IF NOT EXISTS gnosis.search_word_analytics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil varchar(45),
  search_word text
);

CREATE TABLE IF NOT EXISTS gnosis.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200),
  perfil varchar(45),
  senha varchar(45)
);
